version: '2'

services:
  php:
    build:
      context: ./.docker/php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ${SYMFONY_APP_PATH}:/var/www/symfony
      - ${SYMFONY_APP_PATH}/logs/symfony:/var/www/symfony/app/logs
      - ${SYMFONY_APP_PATH}/result:/var/www/symfony/app/result
    environment:
      APP_MAXPROCS: ${APP_MAXPROCS}
    command: composer install
  nginx:
    build: ./.docker/nginx
    ports:
      - 80:80
    volumes_from:
      - php
    volumes:
      - ./logs/nginx/:/var/log/nginx
  rabbit:
    build:
      context: ./.docker/rabbit
    ports:
      - 15672:15672
  supervisor:
    build:
      context: ./.docker/supervisor
    volumes:
      - ${SYMFONY_APP_PATH}:/var/www/symfony
      - ${SYMFONY_APP_PATH}/result:/var/www/symfony/app/result
    environment:
      APP_MAXPROCS: ${APP_MAXPROCS}
    depends_on:
      - php
